export const ybTokenNames = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "success",
  "success-foreground",
  "warning",
  "warning-foreground",
  "info",
  "info-foreground",
  "border",
  "input",
  "ring",
  "font-sans",
  "font-mono",
  "radius-sm",
  "radius-md",
  "radius-lg",
  "radius-xl",
  "shadow-sm",
  "shadow-md",
  "shadow-lg",
  "space-1",
  "space-2",
  "space-3",
  "space-4",
  "space-5",
  "space-6",
  "space-8",
  "space-10",
  "z-dropdown",
  "z-sticky",
  "z-modal",
  "z-toast",
] as const

export type YBTokenName = (typeof ybTokenNames)[number]

export const ybLocaleFontStack =
  'Inter, "PingFang SC", "Microsoft YaHei", "Noto Sans SC", system-ui, sans-serif'
