export const componentCategories = [
  "表单与输入",
  "反馈与状态",
  "浮层与操作",
  "导航与结构",
  "数据与展示",
] as const

export type ComponentCategory = (typeof componentCategories)[number]

export type ComponentCatalogEntry = {
  category: ComponentCategory
  description: string
  href: string
  name: string
  status: "documented" | "planned"
}

export const componentCatalog: readonly ComponentCatalogEntry[] = [
  {
    category: "表单与输入",
    description: "单行文本、数字和密码等原生输入。",
    href: "/docs/components/input",
    name: "Input 输入框",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "录入长文本、说明和消息内容。",
    href: "/docs/components/forms/textarea",
    name: "Textarea 多行输入",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "将标签、说明与校验信息关联到一个控件。",
    href: "/docs/components/forms/field",
    name: "Field 字段",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "切换独立的多选或确认状态。",
    href: "/docs/components/forms/checkbox",
    name: "Checkbox 复选框",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "在少量互斥选项中选择一个值。",
    href: "/docs/components/forms/radio-group",
    name: "RadioGroup 单选组",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "从预定义选项中选择一个值。",
    href: "/docs/components/forms/select",
    name: "Select 选择器",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "立即切换一个布尔设置。",
    href: "/docs/components/forms/switch",
    name: "Switch 开关",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "展示和选择日期的日历视图。",
    href: "/docs/components/forms/calendar",
    name: "Calendar 日历",
    status: "documented",
  },
  {
    category: "表单与输入",
    description: "在输入框与日历之间选择日期。",
    href: "/docs/components/forms/date-picker",
    name: "DatePicker 日期选择",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "在页面内说明成功、风险或需要恢复的状态。",
    href: "/docs/components/feedback/alert",
    name: "Alert 提示",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "展示简短的状态、分类或计数。",
    href: "/docs/components/feedback/badge",
    name: "Badge 徽标",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "说明当前没有内容，并可引导下一步操作。",
    href: "/docs/components/feedback/empty",
    name: "Empty 空状态",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "在内容加载前保留稳定的页面几何。",
    href: "/docs/components/feedback/skeleton",
    name: "Skeleton 骨架屏",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "表示进行中但无法量化的等待状态。",
    href: "/docs/components/feedback/spinner",
    name: "Spinner 加载指示",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "短暂确认用户已完成的非关键操作。",
    href: "/docs/components/feedback/toast",
    name: "Toast 轻提示",
    status: "documented",
  },
  {
    category: "反馈与状态",
    description: "为图标或紧凑控件补充说明。",
    href: "/docs/components/feedback/tooltip",
    name: "Tooltip 文字提示",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "在继续前要求用户确认或完成一项任务。",
    href: "/docs/components/dialog",
    name: "Dialog 对话框",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "从屏幕边缘展开补充内容或操作。",
    href: "/docs/components/overlay/drawer",
    name: "Drawer 抽屉",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "在触发器附近组织一组紧凑操作。",
    href: "/docs/components/overlay/dropdown-menu",
    name: "DropdownMenu 下拉菜单",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "在当前上下文附近展示辅助内容。",
    href: "/docs/components/overlay/popover",
    name: "Popover 弹出层",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "触发明确的用户操作。",
    href: "/docs/components/button",
    name: "Button 按钮",
    status: "documented",
  },
  {
    category: "浮层与操作",
    description: "以图标承载紧凑操作，并提供可访问名称。",
    href: "/docs/components/overlay/icon-button",
    name: "IconButton 图标按钮",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "展示当前页面在信息层级中的位置。",
    href: "/docs/components/navigation/breadcrumb",
    name: "Breadcrumb 面包屑",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "在同一上下文中切换相互关联的内容面板。",
    href: "/docs/components/navigation/tabs",
    name: "Tabs 标签页",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "在明确页码的数据集合中切换页面。",
    href: "/docs/components/navigation/pagination",
    name: "Pagination 分页",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "分隔相邻的内容组或操作区。",
    href: "/docs/components/layout/separator",
    name: "Separator 分隔线",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "沿单一方向组织有节奏的内容。",
    href: "/docs/components/layout/stack",
    name: "Stack 堆叠布局",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "以响应式列组织并列内容。",
    href: "/docs/components/layout/grid",
    name: "Grid 网格布局",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "使用语义标题建立页面层级。",
    href: "/docs/components/layout/heading",
    name: "Heading 标题",
    status: "documented",
  },
  {
    category: "导航与结构",
    description: "统一正文、说明和强调文本。",
    href: "/docs/components/layout/text",
    name: "Text 文本",
    status: "documented",
  },
  {
    category: "数据与展示",
    description: "展示人物或实体的紧凑身份标识。",
    href: "/docs/components/data-display/avatar",
    name: "Avatar 头像",
    status: "documented",
  },
  {
    category: "数据与展示",
    description: "将相关内容与操作组织为一个表面。",
    href: "/docs/components/data-display/card",
    name: "Card 卡片",
    status: "documented",
  },
  {
    category: "数据与展示",
    description: "以语义表格展示结构化、可比较的数据。",
    href: "/docs/components/data-display/table",
    name: "Table 表格",
    status: "documented",
  },
]
